---
## Default Kibana configuration from kibana-docker.
## from https://github.com/elastic/kibana-docker/blob/master/build/kibana/config/kibana.yml
#
server.name: kibana
server.host: "0.0.0.0"
elasticsearch.username: elast
elasticsearch.password: p@ssw0rd!
elasticsearch.url: http://eslb.services.svc.cluster.local:9200
