---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch-client
spec:
  selector:
    matchLabels:
      app: elasticsearch-client
  serviceName: "esclient"
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch-client
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: elk
                operator: In
                values:
                - "true"
      initContainers:
      # NOTE:
      # This is to fix the permission on the volume
      # By default elasticsearch container is not run as
      # non root user.
      # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_notes_for_production_use_and_defaults
      - name: fix-the-volume-permission
        image: busybox
        command:
        - sh
        - -c
        - chmod -R 777 /var/lib/elasticsearch/ && chown -R 1000:1000 /var/lib/elasticsearch/
        securityContext:
          privileged: true
        volumeMounts:
        - name: es-persistent-storage
          mountPath: /var/lib/elasticsearch
      containers:
      - image: patt1293/elasticsearch-client:latest
        imagePullPolicy: Always
        name: elasticsearch-client
        ports:
        - containerPort: 9200
          name: 9200tcp01
          protocol: TCP
        - containerPort: 9300
          name: transport
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/elasticsearch
          name: es-persistent-storage
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: dockerhub
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
            - name: es-persistent-storage
              persistentVolumeClaim:
                claimName: es-client-claim
