apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["deployment:services:backend-api"]'
    external-dns.alpha.kubernetes.io/hostname: backend-api.external-dns.cambae.io
  name: api
  labels:
    run: api
spec:
  ports:
  - name: 6902tcp02
    port: 6902
    protocol: TCP
  selector:
    run: api
