apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["deployment:services:logstash"]'
  name: logstash
  labels:
    run: logstash
spec:
  ports:
    - port: 5044
      name: 5044tcp01
      protocol: TCP
    - port: 5044
      name: 5044udp01
      protocol: UDP
  selector:
    run: logstash
